apiVersion: apps/v1
kind: Deployment
metadata:
  name: humanity-against-covid19-test-back
  namespace: default
spec:
  selector:
    matchLabels:
      app: humanity-against-covid19-test-back
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app: humanity-against-covid19-test-back
    spec:
      containers:
      - name: humanity-against-covid19-test-back
        image: humanityagainstcovid19/test-back:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: humanity-against-covid19-test-back
  namespace: default
spec:
  selector:
    app: humanity-against-covid19-test-back
  ports:
    - port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
  name: humanity-against-covid19-test-back
  namespace: default
spec:
  rules:
  - host: humanityagainstcovid19.com
    http:
      paths:
      - path: /api
        backend:
          serviceName: humanity-against-covid19-test-back
          servicePort: 80
