name: Build nodejs and deploy to kubernetes

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: yarn install
        run: yarn install

      - name: yarn build
        run: yarn prodBuild

      - uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: humanityagainstcovid19/frontend
          tag: ${GITHUB_RUN_ID}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.DO_KUBECONFIG }}
        id: setcontext

      - uses: Azure/k8s-deploy@v1
        with:
          namespace: 'default'
          manifests: |
              deploy/deployment.yaml
          images: 'humanityagainstcovid19/frontend:${{ github.run_id }}'
          kubectl-version: latest
